# https://taskfile.dev

version: '3'

vars:
  DOCKER_COMPOSE: "docker-compose"
  DOCKER_COMPOSE_ARGS: "--project-name eda --file tools/docker/docker-compose.yml"

tasks:
  default:
    desc: "Show this message and exit"
    cmds:
      - task -l
    silent: true

  lint:
    desc: "Run all linters."
    cmds:
      - task: lint:black
      - task: lint:isort
      - task: lint:flake8

  test:
    desc: "Run project tests."
    cmds:
      - python -m pytest

  lint:black:
    desc: "Check code with `black`."
    cmds:
      - black --check .

  lint:isort:
    desc: "Check code with `isort`."
    cmds:
      - isort --check .

  lint:flake8:
    desc: "Check code with `flake8`."
    cmds:
      - flake8

  format:
    desc: "Run all code formatters."
    cmds:
      - task: format:isort
      - task: format:black

  format:isort:
    desc: "Format code with `isort`."
    cmds:
      - isort .

  format:black:
    desc: "Format code with `black`."
    cmds:
      - black .

  docker:
    desc: "Run docker-compose with specified CLI arguments."
    summary: |
      Run docker-compose with specified CLI arguments.
      
      Example:
        $ task docker -- ls
    cmds:
      - '{{.DOCKER_COMPOSE}} {{.DOCKER_COMPOSE_ARGS}} {{.CLI_ARGS}}'

  docker:build:
    desc: "Build container images."
    cmds:
      - task: docker
        vars:
          CLI_ARGS: build

  docker:up:
    desc: "Start all services."
    cmds:
      - task: docker
        vars:
          CLI_ARGS: up --detach

  docker:up:postgres:
    desc: "Start PostgreSQL service."
    cmds:
      - task: docker
        vars:
          CLI_ARGS: up --detach postgres

  docker:down:
    desc: "Stop all services."
    cmds:
      - task: docker
        vars:
          CLI_ARGS: down

  docker:purge:
    desc: "Stop all containers and delete all volumes."
    cmds:
      - task: docker
        vars:
          CLI_ARGS: down --volumes

  minikube:build:
    desc: "Build docker image and push to minikube"
    cmds:
      - scripts/eda_kube.sh build {{.CLI_ARGS}}

  minikube:deploy:
    desc: "Build deployment and deploy to minikube"
    deps: [minikube:clean]
    cmds:
      - scripts/eda_kube.sh deploy {{.CLI_ARGS}}

  minikube:clean:
    desc: "Clean deployment directory and clean minikube resources"
    cmds:
      - scripts/eda_kube.sh clean

  minikube:fp:ui:
    desc: "forward local port to ui instance port in minikube"
    cmds:
      - scripts/eda_kube.sh port-forward-ui {{.CLI_ARGS}}

  minikube:all:
    desc: "build, deploy, and portforward UI"
    cmds:
      - task: minikube:build
      - task: minikube:deploy
      - task: minikube:fp:ui