"""project table add fields

Revision ID: adddd9c9d096
Revises: 0a069266ef71
Create Date: 2022-08-24 18:58:00.287195+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "adddd9c9d096"
down_revision = "0a069266ef71"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("project", sa.Column("name", sa.String(), nullable=True))
    op.add_column(
        "project", sa.Column("description", sa.String(), nullable=True)
    )
    op.add_column(
        "project",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "project",
        sa.Column("modified_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("project", "modified_at")
    op.drop_column("project", "created_at")
    op.drop_column("project", "description")
    op.drop_column("project", "name")
    # ### end Alembic commands ###
