apiVersion: apps/v1
kind: Deployment
metadata:
  name: ansible-events-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ansible-events-ui
  strategy: {}
  template:
    metadata:
      labels:
        app: ansible-events-ui
    spec:
      containers:
        - args:
            - /bin/bash
            - -c
            - alembic upgrade head && ansible-events-ui
          env:
            - name: AE_DATABASE_URL
              value: postgresql+asyncpg://postgres:secret@postgres/ansible_events
            - name: AE_HOST
              value: 0.0.0.0
          image: ansible-events-ui
          imagePullPolicy: Never
          name: ansible-events-ui
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
