apiVersion: v1
kind: Service
metadata:
  name: ansible-events-ui
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
      app: ansible-events-ui
status:
  loadBalancer: {}
