version: '3.9'

services:
  app:
    image: ansible-events-ui
    build:
      context: ../../
      dockerfile: tools/docker/Dockerfile
    command: ["/bin/bash", "-c", "alembic upgrade head && ansible-events-ui"]
    ports:
      - "8080:8080"
    environment:
      - AE_HOST=0.0.0.0
      - AE_DATABASE_URL=postgresql+asyncpg://postgres:secret@postgres/ansible_events
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: "docker.io/library/postgres:13"
    environment:
      - "POSTGRES_PASSWORD=secret"
      - "POSTGRES_DB=ansible_events"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
volumes:
  postgres_data:
