name: Test docker deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-docker-deployment:
    runs-on: ubuntu-latest
    env:
      EDA_TOKEN: ${{ secrets.EDA_SERVER_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy docker-compose and test it
        working-directory: tools/docker
        run: |
          export GITHUB_TOKEN=$EDA_TOKEN
          echo "the token is $GITHUB_TOKEN"
          docker-compose up -d --build
          curl -q http://localhost:8080/ping
          curl -q http://localhost:8080/eda
