name: Test docker deployment

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test-docker-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy docker-compose and test it
        working-directory: tools/docker
        run: |
          docker-compose up -d --build
          curl -v -q --fail -o /dev/null http://localhost:9000/ping
          curl -v -q --fail -o /dev/null http://localhost:8080/eda/index.html
